/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#095300",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#107100",
        "on-tertiary-fixed-variant": "#852400",
        "primary": "#50604b",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "background": "#fcf9f8",
        "tertiary-fixed": "#ffdbd0",
        "on-surface": "#1c1b1b",
        "on-tertiary-container": "#fffbff",
        "surface-container": "#f0eded",
        "on-secondary-fixed": "#022100",
        "secondary": "#106e00",
        "outline": "#747871",
        "on-secondary": "#ffffff",
        "tertiary-container": "#d43f00",
        "surface-dim": "#dcd9d9",
        "on-error-container": "#93000a",
        "on-primary-container": "#f8fff0",
        "on-background": "#1c1b1b",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3b4b37",
        "inverse-surface": "#313030",
        "surface": "#fcf9f8",
        "on-tertiary-fixed": "#3a0b00",
        "inverse-primary": "#baccb2",
        "outline-variant": "#c4c8bf",
        "secondary-fixed": "#79ff5b",
        "surface-tint": "#53634e",
        "tertiary-fixed-dim": "#ffb59e",
        "secondary-container": "#38fe13",
        "secondary-fixed-dim": "#2ae500",
        "primary-fixed": "#d6e8cd",
        "tertiary": "#aa3000",
        "primary-container": "#697963",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container-high": "#eae7e7",
        "on-primary-fixed": "#111f0f",
        "on-surface-variant": "#444841",
        "surface-bright": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed-dim": "#baccb2",
        "surface-variant": "#e5e2e1",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "40px",
        "shadow-offset": "4px",
        "margin-mobile": "16px",
        "unit": "4px"
      },
      fontFamily: {
        "label-bold": ["JetBrains Mono"],
        "headline-lg": ["Archivo Narrow"],
        "headline-lg-mobile": ["Archivo Narrow"],
        "display-lg": ["Archivo Narrow"],
        "headline-md": ["Archivo Narrow"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "label-bold": ["12px", { lineHeight: "1.4", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
