# Generated by Django 5.2.16 on 2026-07-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentscore',
            unique_together={('department', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='overallesgscore',
            unique_together={('date',)},
        ),
    ]
