# Generated by Django 5.2.16 on 2026-07-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_api', '0002_alter_departmentscore_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='environmentalscore',
            unique_together={('department', 'date')},
        ),
    ]
